name: Test CV Web
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start API and Monitor Log
        # Chỉ định luôn là làm việc trong thư mục api
        working-directory: ./api 
        run: |
          nohup python -u -m uvicorn api:app --host 127.0.0.1 --port 8000 > server.log 2>&1 &
          timeout 300s sh -c 'until grep -q "Application startup complete" server.log; do sleep 2; done' || true
          cat server.log
      - name: Run Test Unhappy case
        run: |
          npx playwright install --with-deps chromium
          node auth.js
          npx playwright test tests/unhappy.spec.js
      - name: Upload Screenshots and Logs
        if: always() # <--- DÒNG NÀY LÀ SỐNG CÒN!
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts # Tên cái file zip bạn sẽ tải về
          path: |
            output/
            server.log
            playwright-report/
          retention-days: 7
      # - name: Run Test Happy case
      #   run: |
      #     npx playwright test tests/generated-from-testcase.spec.js
